name: Hello

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Run install
        run: npm install
      - name: Run test
        run: npm test
      - name: Run build
        run: npm run build
